- name: Configure all hosts
  hosts: all
  become: true
  roles:
    - common

- name: Configure database
  hosts: db
  become: true
  roles:
    - db

- name: Configure worker
  hosts: workers
  become: true
  roles:
    - app
    - nginx